# Generated by Django 5.1.6 on 2025-03-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=20)),
                ('launch_date', models.DateField()),
                ('image', models.ImageField(default='/default.jpg', upload_to='cars_images')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
            ],
        ),
    ]
