# Generated by Django 5.1.6 on 2025-03-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='cars_images'),
        ),
    ]
