# Generated by Django 5.1.6 on 2025-03-11 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addtocart', '0002_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
